---

- name: Get Raspberry Pi type
  ansible.builtin.shell: "raspi-config nonint get_pi_type"
  register: pi_type
  changed_when: False

- name: Show pi version
  ansible.builtin.debug:
    msg: "Pi version: {{ pi_type.stdout }}"
    verbosity: 1
