---

# Based on https://levelup.gitconnected.com/extend-the-lifespan-of-your-raspberry-pis-sd-card-with-log2ram-5929bf3316f2

- name: Clone the log2ram repository
  ansible.builtin.git:
    repo: 'https://github.com/azlux/log2ram.git'
    dest: /tmp/log2ram

- name: Install log2ram
  become: yes
  ansible.builtin.command:
    cmd: 'cd /tmp/log2ram && ./install.sh'

- name: Cleanup installation files
  ansible.builtin.file:
    path: /tmp/log2ram
    state: absent
